name: Deploy to EC2

on:
  push:
    branches:
      - main




jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4


      - name: graldew에 실행 권한 부여
        run: chmod +x gradlew

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -x test


      - name: 빌드 결과물 jar 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar project.jar

      # 7. EC2에 jar 파일 전송
      - name: EC2로 jar 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/app

      # 8. EC2에 접속 후 jar 실행
      - name: EC2에 접속해서 실행하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          timeout: 900          # 15분
          command_timeout: 900  # 15분
          script: |
            set -e
            cd /home/ubuntu/app
            pkill -f 'project.jar' || true
            sleep 1
            
            # 자바 절대경로로 실행(환경파일 로딩 같은 거 안 함)
            JAVA_BIN=/usr/bin/java
            "$JAVA_BIN" -version
            
            nohup "$JAVA_BIN" -jar project.jar \
              --server.address=0.0.0.0 --server.port=8080 \
              > app.log 2>&1 &
            
            sleep 8
            if pgrep -fa 'project.jar' >/dev/null; then
              echo "APP RUNNING"
            else
              echo "APP NOT RUNNING"
              tail -n 200 app.log || true
              exit 1
            fi
